# TreasureChests Configuration

# The chance (out of 1.0) that a treasure chest will drop when a valid block is broken.
# For example, 0.05 is a 5% chance.
drop-chance: 0.05

# The message broadcast to the server when a treasure chest is found.
# Use %player% for the player's name and %tier% for the chest tier.
broadcast-message: "&6&lSCHATZFUND! &e%player% &7hat eine &e%tier% &7Schatztruhe gefunden!"

# Whether to broadcast the message above when a chest is found.
broadcast-message-toggle: true

# A list of blocks that can drop a treasure chest when broken.
allowed-blocks:
  - "STONE"
  - "DEEPSLATE"
  - "DIORITE"
  - "ANDESITE"
  - "GRANITE"

# loot-tables defines the loot found in treasure chests.
loot-tables:
  # 'rolls' determines how many times the plugin tries to add an item to the chest.
  rolls: "3-5"

  # Tiers define the different types of treasure chests that can be found.
  tiers:
    common:
      display-name: "&aGewöhnliche Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.50
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: false
      animations:
        spawn:
          sound: { name: "BLOCK_CHEST_OPEN", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          sound: { name: "BLOCK_CHEST_CLOSE", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "IRON_INGOT"
          amount: "5-10"
          chance: 0.8
        - material: "BREAD"
          amount: "3-5"
          chance: 1.0
        - material: "COAL"
          amount: "4-8"
          chance: 0.9
    rare:
      display-name: "&9Seltene Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.25
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: false
      animations:
        spawn:
          sound: { name: "BLOCK_CHEST_OPEN", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          sound: { name: "BLOCK_CHEST_CLOSE", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "GOLDEN_APPLE"
          amount: 1
          chance: 0.7
        - material: "DIAMOND"
          amount: "1-3"
          chance: 0.5
        - material: "IRON_PICKAXE"
          amount: 1
          chance: 0.4
    epic:
      display-name: "&5Epische Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.15
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: true
      animations:
        spawn:
          sound: { name: "BLOCK_CHEST_OPEN", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          sound: { name: "BLOCK_CHEST_CLOSE", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "DIAMOND_SWORD"
          amount: 1
          chance: 0.4
        - material: "TOTEM_OF_UNDYING"
          amount: 1
          chance: 0.2
        - material: "EXPERIENCE_BOTTLE"
          amount: "8-16"
          chance: 0.8
    legendary:
      display-name: "&6Legendäre Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.08
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: true
      animations:
        spawn:
          sound: { name: "BLOCK_CHEST_OPEN", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          sound: { name: "BLOCK_CHEST_CLOSE", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "NETHERITE_INGOT"
          amount: "1-2"
          chance: 0.3
        - material: "ELYTRA"
          amount: 1
          chance: 0.1
        - material: "BEACON"
          amount: 1
          chance: 0.05
    mythical:
      display-name: "&dMythische Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.02
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: true
      animations:
        spawn:
          sound: { name: "BLOCK_CHEST_OPEN", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          sound: { name: "BLOCK_CHEST_CLOSE", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "NETHER_STAR"
          amount: 1
          chance: 0.2
        - material: "ENCHANTED_GOLDEN_APPLE"
          amount: 1
          chance: 0.1
        - material: "DRAGON_EGG"
          amount: 1
          chance: 0.01
